### ISSUE TITLE
Use the Inria Sans font family from GF for all typography

### ISSUE THREAD

**Issue by justvanrossum** [gferreira/fontra-docs#3]
This is the "official" Fontra UI typeface. Would be nice if the docs would use it, too.

This could be a task for @fatih-erikli.

I think it's fine to use google-hosted fonts for this:
- https://fonts.google.com/specimen/Inria+Sans

I don't know how the styling works in this system. Maybe it is easy to figure out, or else maybe @gferreira can give a hint.

**Comment by gferreira** [comment]
hello Just, thanks for the request. [this was already implemented](http://gferreira.github.io/fontra-docs/) :) see [css/style.sass](http://github.com/gferreira/fontra-docs/blob/main/css/style.sass)

I wrote some notes about the documentation infra-structure here: [Documentation overview](http://gferreira.github.io/fontra-docs/topics/documentation/)

**Comment by justvanrossum** [comment]
Thanks so much, I had completely missed that!
