### ISSUE TITLE
Icons can be taken from the Fontra repo

### ISSUE THREAD

**Issue by justvanrossum** [gferreira/fontra-docs#5]
I noticed a DrawBot script in this repo to export SVG from the source UFO. However, that doesn't cover everything, as we started using icons from the [Tabler](https://tabler-icons.io/) collection.

Also, everything is available as SVG in the repo:
- Custom designs, as SVG, derived from UFO: https://github.com/googlefonts/fontra/tree/main/src/fontra/client/images
- The Tabler icons we use: https://github.com/googlefonts/fontra/tree/main/src/fontra/client/tabler-icons

Perhaps we need a script that just grabs the SVG files from both folders.

**Comment by justvanrossum** [comment]
Directory contents in json form:
- https://api.github.com/repos/googlefonts/fontra/contents/src/fontra/client/images
- https://api.github.com/repos/googlefonts/fontra/contents/src/fontra/client/tabler-icons

**Comment by gferreira** [comment]
the SVG icons are now collected from (a local copy of) the main Fontra repository, see [collect-icons.py](https://github.com/gferreira/fontra-docs/blob/main/_py/collect-icons.py)

**Comment by justvanrossum** [comment]
Thanks! While this is better than nothing, it ties the workflow to you personal setup, making you the sole person who can update. Good enough for now, but not ideal in the longer term.

**Comment by gferreira** [comment]
[improved script](https://github.com/gferreira/fontra-docs/blob/main/_py/collect-icons.py), now it should work everywhere. thanks
